### PR TITLE
Update README.md with a Django example

### PR DESCRIPTION
**Pull request by devxpy**
I am using this in production, so thought I should share how others can use it as well.

### CODE REVIEW

**Comment by devxpy** [comment]
I guess it's a different approach to doing the same thing?

I like mine better because it creates an all in one package that does everything to start the thing.

For example, I recently created a telegram bot, and along with runserver/gunicorn I also had to start the bot using a custom management command. So I simply launched a Multiprocessing process to do all my tasks...

P.S. Your pipenv command will package all dependencies, including the development one's, which is probably not what you want?

**Comment by sixninetynine** [comment]
Hi @devxpy 

Thanks for the PR! Instead of adding this to the README, what do you think about creating an "examples" section in the documentation and putting this there? I feel like having a few practical example usages or how-tos (such as this one) would be super valuable to a lot of folks.

**Comment by devxpy** [comment]
Will do

**Comment by devxpy** [comment]
Moved to https://github.com/linkedin/shiv/pull/68

**Pull request closed without merging**
