### PR TITLE
Add an option to pass the zipapp site-packages to subprocesses

### PR DESCRIPTION
**Pull request by pfmoore**
Fix for #40 and #74

### CODE REVIEW

**Comment by pfmoore** [comment]
I'm not sure how to fix the coverage complaint - the test does exercise the new code, but probably only by running a zipapp in a subprocess (I say "probably" because the coverage report doesn't tell me what's not covered - it points at stuff in `.tox` and says "Source not available" 😢 )

**Comment by sixninetynine** [comment]
@pfmoore yeah, yet another reason why I want to refactor some stuff so it's _easier_ to test and so that coverage can be more accurately reported

**Comment by pfmoore** [comment]
Blast - conflict with my other PR. I'll fix that now.

**Comment by pfmoore** [comment]
Fixed - sorry about that

**Comment by sixninetynine** [comment]
thanks!! there's a bug I introduced in #70 once I squash it I'll cut a new pypi release

**Comment by pfmoore** [comment]
Thanks for the fast turnaround - much appreciated!

**Comment by sixninetynine** [comment]
on pypi @ 0.0.38 ✨

**Pull request merged**
